variable "project" {}
variable "environment" {}
variable "primary_cidr" {}
variable "cidrs" {}
variable "public_subnets" {}
variable "public_lb_subnets" {}
variable "control_plane_subnets" {}
variable "internal_lb_subnets" {}
variable "tgw_subnets" {}
variable "private_nat_subnets" {}
variable "efs_subnets" {}
variable "utility_subnets" {}
variable "db_subnets" {}
variable "node_group_subnets" {}